# LaraCraft — Jade / Stone / Antique Gold (kitty)
font_family MesloLGSDZ Nerd Font Mono
font_size 11.0
background_opacity 0.96
window_padding_width 10
confirm_os_window_close 0

foreground #E3DCC8
background #121A19
selection_foreground #F0F5EE
selection_background #2E4A44
cursor #D9B36C
url_color #7EC8D3

color0 #24312F
color8 #8A948E
color1 #D97D7D
color9 #D97D7D
color2 #9DC08B
color10 #A8E6C5
color3 #D9B36C
color11 #D9B36C
color4 #7EC8D3
color12 #7EC8D3
color5 #B8A9D9
color13 #B8A9D9
color6 #7ED3AE
color14 #7ED3AE
color7 #E3DCC8
color15 #F0F5EE
